### ISSUE TITLE
SSL: WRONG_VERSION_NUMBER

### ISSUE THREAD

**Issue by MS-Jahan** [ikvk/imap_tools#111]
Code:

```
from imap_tools import MailBox, AND

with MailBox(host='localhost', port=1143, timeout=20).login('<user>', '<password>') as mailbox:
    # get unseen emails from INBOX folder
    for msg in mailbox.fetch(AND(seen=False)):
        print(msg.date, len(msg.html or msg.text))
```

Error I'm getting:
```
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/email_client.py", line 5, in <module>
    with MailBox(host='localhost', port=1143, timeout=20).login('<user>', '<password>', 'INBOX') as mailbox:
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/imap_tools/mailbox.py", line 259, in __init__
    super().__init__()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/imap_tools/mailbox.py", line 27, in __init__
    self.box = self._get_mailbox_client()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/imap_tools/mailbox.py", line 276, in _get_mailbox_client
    return imaplib.IMAP4_SSL(self._host, self._port, self._keyfile,  # noqa
  File "/data/data/com.termux/files/usr/lib/python3.9/imaplib.py", line 1324, in __init__
    IMAP4.__init__(self, host, port, timeout)
  File "/data/data/com.termux/files/usr/lib/python3.9/imaplib.py", line 202, in __init__
    self.open(host, port, timeout)
  File "/data/data/com.termux/files/usr/lib/python3.9/imaplib.py", line 1337, in open
    IMAP4.open(self, host, port, timeout)
  File "/data/data/com.termux/files/usr/lib/python3.9/imaplib.py", line 312, in open
    self.sock = self._create_socket(timeout)
  File "/data/data/com.termux/files/usr/lib/python3.9/imaplib.py", line 1328, in _create_socket
    return self.ssl_context.wrap_socket(sock,
  File "/data/data/com.termux/files/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/data/data/com.termux/files/usr/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/data/data/com.termux/files/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)
```
I'm running this code in Termux app (Linux terminal emulator app for Android). I'm running a local email server with no ssl. To be specific, I'm using [this](https://github.com/emersion/hydroxide).
Username, password, port and host are right, worked with Android client.

How to solve this problem?

**Comment by ikvk** [comment]
https://docs.python.org/3/library/ssl.html

... This module uses the OpenSSL library.

May be problem at your system?

**Comment by MS-Jahan** [comment]
Okay, I'll try on my PC and will let you know.

**Comment by MS-Jahan** [comment]
Sorry for being late. I've tried the same code on my Arch machine. Produces the same error. What could be wrong?

**Comment by ikvk** [comment]
Have you try to update ssl libs/os?

**Comment by MS-Jahan** [comment]
I'm using Arch Linux and the system in updated every day. These packages related to ssl are installed in the system:

![image](https://user-images.githubusercontent.com/27774290/112423694-5572e480-8d5d-11eb-8b86-bdc149bebb33.png)

`openssl version -a` command shows this output:

```
OpenSSL 1.1.1j  16 Feb 2021
built on: Wed Feb 17 14:35:49 2021 UTC
platform: linux-x86_64
options:  bn(64,64) rc4(16x,int) des(int) idea(int) blowfish(ptr) 
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wa,--noexecstack -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DNDEBUG -D_FORTIFY_SOURCE=2
OPENSSLDIR: "/etc/ssl"
ENGINESDIR: "/usr/lib/engines-1.1"
Seeding source: os-specific
```

**Comment by ikvk** [comment]
what about this? https://stackoverflow.com/questions/57715289/

**Comment by MS-Jahan** [comment]
> what about this? https://stackoverflow.com/questions/57715289/ (the essence)

I've tried this before. But same result.

**Comment by ikvk** [comment]
Why are you need tls if you are using localhost?

**Comment by MS-Jahan** [comment]
I don't need tls or ssl. The local server doesn't have it.

**Comment by ikvk** [comment]
So, what about MailBoxUnencrypted?

**Comment by MS-Jahan** [comment]
> So, what about MailBoxUnencrypted?

It's working. Thank you so much.
