### ISSUE TITLE
Cooperate with rsocks package for connecting to gmail through a local sock5 reverse proxy server forwarder.

### ISSUE THREAD

**Issue by hongyi-zhao** [ikvk/imap_tools#128]
Currently, I noticed the [rsocks](https://github.com/tonyseek/rsocks) package, which is able to act as a SOCKS 4/5 reverse proxy server, as described by [the following code](https://github.com/tonyseek/rsocks#api-overview):

```python
import os

from rsocks.pool import ServerPool
from rsocks.server import ReverseProxyServer

proxy = os.environ.get('SOCKS_PROXY', 'socks5://localhost:1080')
pool = ServerPool()

with pool.new_server(
        name='IMAP',
        server_class=ReverseProxyServer,
        upstream=('imap.gmail.com', 993),
        use_ssl=True) as server:
    server.set_proxy(proxy)
    server.listen(('127.0.0.1', 5993))

with pool.new_server(
        name='SMTP',
        server_class=ReverseProxyServer,
        upstream=('smtp.gmail.com', 465),
        use_ssl=True) as server:
    server.set_proxy(proxy)
    server.listen(('127.0.0.1', 5465))

if __name__ == '__main__':
    pool.loop()
```
So, I want to know if I can let imap_tools cooperate with rsocks package for connecting to gmail through a local sock5 reverse proxy server forwarder.
 
Regards,
HY

**Comment by ikvk** [comment]
https://github.com/ikvk/imap_tools/blob/master/examples/pysocks_proxy.py

Have you see it?

**Comment by hongyi-zhao** [comment]
I tested this example directly with my socks5 proxy, but failed, as I've filed the issue [here](https://github.com/ikvk/imap_tools/issues/127). The testing code is as follows:

```python
"""
MailBox traffic through proxy servers using https://github.com/Anorov/PySocks
This logic will not be part of imap_tools
"""
import ssl
import socks
from imaplib import IMAP4

from imap_tools import BaseMailBox, MailBoxUnencrypted


class Imap4Proxy(IMAP4):
    def __init__(self,
                 host: str = "",
                 port: int = 143,
                 p_timeout: int = None,
                 p_source_address: tuple = None,
                 p_proxy_type: socks.PROXY_TYPES = socks.SOCKS5,
                 p_proxy_addr: str = None,
                 p_proxy_port: int = None,
                 p_proxy_rdns=True,
                 p_proxy_username: str = None,
                 p_proxy_password: str = None,
                 p_socket_options: iter = None,
                 ):
        self._host = host
        self._port = port
        self._p_timeout = p_timeout
        self._p_source_address = p_source_address
        self._p_proxy_type = p_proxy_type
        self._p_proxy_addr = p_proxy_addr
        self._p_proxy_port = p_proxy_port
        self._p_proxy_rdns = p_proxy_rdns
        self._p_proxy_username = p_proxy_username
        self._p_proxy_password = p_proxy_password
        self._p_socket_options = p_socket_options
        super().__init__(host, port)

    def _create_socket(self):
        return socks.create_connection(
            dest_pair=(self._host, self._port),
            timeout=self._p_timeout,
            source_address=self._p_source_address,
            proxy_type=self._p_proxy_type,
            proxy_addr=self._p_proxy_addr,
            proxy_port=self._p_proxy_port,
            proxy_rdns=self._p_proxy_rdns,
            proxy_username=self._p_proxy_username,
            proxy_password=self._p_proxy_password,
            socket_options=self._p_socket_options,
        )


class Imap4SslProxy(Imap4Proxy):
    def __init__(self,
                 host: str = "",
                 port: int = 993,
                 keyfile=None,
                 certfile=None,
                 ssl_context=None,
                 p_timeout: int = None,
                 p_source_address: tuple = None,
                 p_proxy_type: socks.PROXY_TYPES = socks.SOCKS5,
                 p_proxy_addr: str = None,
                 p_proxy_port: int = None,
                 p_proxy_rdns=True,
                 p_proxy_username: str = None,
                 p_proxy_password: str = None,
                 p_socket_options: iter = None,
                 ):
        self._host = host
        self._port = port
        self._p_timeout = p_timeout
        self._p_source_address = p_source_address
        self._p_proxy_type = p_proxy_type
        self._p_proxy_addr = p_proxy_addr
        self._p_proxy_port = p_proxy_port
        self._p_proxy_rdns = p_proxy_rdns
        self._p_proxy_username = p_proxy_username
        self._p_proxy_password = p_proxy_password
        self._p_socket_options = p_socket_options

        if ssl_context is not None and keyfile is not None:
            raise ValueError("ssl_context and keyfile arguments are mutually exclusive")
        if ssl_context is not None and certfile is not None:
            raise ValueError("ssl_context and certfile arguments are mutually exclusive")
        if keyfile is not None or certfile is not None:
            import warnings
            warnings.warn("keyfile and certfile are deprecated, use ssl_context instead", DeprecationWarning, 2)

        if ssl_context is None:
            ssl_context = ssl._create_stdlib_context(certfile=certfile, keyfile=keyfile)  # noqa

        self.keyfile = keyfile
        self.certfile = certfile
        self.ssl_context = ssl_context

        super().__init__(host, port, p_timeout, p_source_address, p_proxy_type, p_proxy_addr, p_proxy_port,
                         p_proxy_rdns, p_proxy_username, p_proxy_password, p_socket_options)

    def _create_socket(self):
        sock = super()._create_socket()
        server_hostname = self.host if ssl.HAS_SNI else None
        return self.ssl_context.wrap_socket(sock, server_hostname=server_hostname)

    def open(self, host='', port=993):
        super().open(host, port)


class MailBoxUnencryptedProxy(MailBoxUnencrypted):
    """Working with the email box through IMAP4 through proxy"""

    def __init__(self,
                 host: str = "",
                 port: int = 143,
                 p_timeout: int = None,
                 p_source_address: tuple = None,
                 p_proxy_type: socks.PROXY_TYPES = socks.SOCKS5,
                 p_proxy_addr: str = None,
                 p_proxy_port: int = None,
                 p_proxy_rdns=True,
                 p_proxy_username: str = None,
                 p_proxy_password: str = None,
                 p_socket_options: iter = None,
                 ):
        self._host = host
        self._port = port
        self._p_timeout = p_timeout
        self._p_source_address = p_source_address
        self._p_proxy_type = p_proxy_type
        self._p_proxy_addr = p_proxy_addr
        self._p_proxy_port = p_proxy_port
        self._p_proxy_rdns = p_proxy_rdns
        self._p_proxy_username = p_proxy_username
        self._p_proxy_password = p_proxy_password
        self._p_socket_options = p_socket_options
        super().__init__()

    def _get_mailbox_client(self):
        return Imap4Proxy(
            self._host, self._port,
            self._p_timeout, self._p_source_address, self._p_proxy_type, self._p_proxy_addr, self._p_proxy_port,
            self._p_proxy_rdns, self._p_proxy_username, self._p_proxy_password, self._p_socket_options)


class MailBoxProxy(BaseMailBox):
    """Working with the email box through IMAP4 over SSL connection through proxy"""

    def __init__(self,
                 host: str = "",
                 port: int = 993,
                 keyfile=None,
                 certfile=None,
                 ssl_context=None,
                 p_timeout: int = None,
                 p_source_address: tuple = None,
                 p_proxy_type: socks.PROXY_TYPES = socks.SOCKS5,
                 p_proxy_addr: str = None,
                 p_proxy_port: int = None,
                 p_proxy_rdns=True,
                 p_proxy_username: str = None,
                 p_proxy_password: str = None,
                 p_socket_options: iter = None,
                 ):
        self._host = host
        self._port = port
        self._keyfile = keyfile
        self._certfile = certfile
        self._ssl_context = ssl_context
        self._p_timeout = p_timeout
        self._p_source_address = p_source_address
        self._p_proxy_type = p_proxy_type
        self._p_proxy_addr = p_proxy_addr
        self._p_proxy_port = p_proxy_port
        self._p_proxy_rdns = p_proxy_rdns
        self._p_proxy_username = p_proxy_username
        self._p_proxy_password = p_proxy_password
        self._p_socket_options = p_socket_options
        super().__init__()

    def _get_mailbox_client(self):
        return Imap4SslProxy(
            self._host, self._port, self._keyfile, self._certfile, self._ssl_context,
            self._p_timeout, self._p_source_address, self._p_proxy_type, self._p_proxy_addr, self._p_proxy_port,
            self._p_proxy_rdns, self._p_proxy_username, self._p_proxy_password, self._p_socket_options)


if __name__ == '__main__':
    with MailBoxProxy(p_proxy_type=socks.SOCKS5,
                      p_proxy_addr='127.0.0.1',  # zproxy.lum-superproxy.io
                      p_proxy_port=18889,  # 22225
                      p_proxy_username='',
                      p_proxy_password='',
                      p_timeout=10,
                      host='imap.gmail.com').login('my_user_account@gmail.com', 'my_pwd', 'INBOX') as mailbox:
        for msg in mailbox.fetch():
            print(msg.subject, msg.date_str)
```

See the following errors given by python 3.8 and 3.9:

```
$ pyenv shell datasci 
(datasci) werner@X10DAi:~/Public/repo/github.com/ikvk/imap_tools.git/examples$ python pysocks_proxy.py 
Traceback (most recent call last):
  File "/home/werner/Public/repo/github.com/ikvk/imap_tools.git/examples/pysocks_proxy.py", line 189, in <module>
    with MailBoxProxy(p_proxy_type=socks.SOCKS5,
  File "/home/werner/Public/repo/github.com/ikvk/imap_tools.git/examples/pysocks_proxy.py", line 179, in __init__
    super().__init__()
  File "/home/werner/.pyenv/versions/datasci/lib/python3.9/site-packages/imap_tools/mailbox.py", line 28, in __init__
    self.box = self._get_mailbox_client()
  File "/home/werner/Public/repo/github.com/ikvk/imap_tools.git/examples/pysocks_proxy.py", line 182, in _get_mailbox_client
    return Imap4SslProxy(
  File "/home/werner/Public/repo/github.com/ikvk/imap_tools.git/examples/pysocks_proxy.py", line 98, in __init__
    super().__init__(host, port, p_timeout, p_source_address, p_proxy_type, p_proxy_addr, p_proxy_port,
  File "/home/werner/Public/repo/github.com/ikvk/imap_tools.git/examples/pysocks_proxy.py", line 37, in __init__
    super().__init__(host, port)
  File "/home/werner/.pyenv/versions/3.9.1/lib/python3.9/imaplib.py", line 202, in __init__
    self.open(host, port, timeout)
TypeError: open() takes from 1 to 3 positional arguments but 4 were given

$ pyenv shell socks5-haproxy 
(socks5-haproxy) werner@X10DAi:~/Public/repo/github.com/ikvk/imap_tools.git/examples$ python pysocks_proxy.py 
Traceback (most recent call last):
  File "pysocks_proxy.py", line 189, in <module>
    with MailBoxProxy(p_proxy_type=socks.SOCKS5,
  File "/home/werner/.pyenv/versions/socks5-haproxy/lib/python3.8/site-packages/imap_tools/mailbox.py", line 40, in login
    login_result = self.box.login(username, password)
  File "/home/werner/.pyenv/versions/3.8.3/lib/python3.8/imaplib.py", line 603, in login
    raise self.error(dat[-1])
imaplib.error: b'[AUTHENTICATIONFAILED] Invalid credentials (Failure)'

```

**Comment by ikvk** [comment]
Seems this https://github.com/ikvk/imap_tools/issues/76 

You may fix example

**Comment by hongyi-zhao** [comment]
Still not clear. In my above testing, this parameter has been used:

```python
if __name__ == '__main__':
    with MailBoxProxy(p_proxy_type=socks.SOCKS5,
                      p_proxy_addr='127.0.0.1',  # zproxy.lum-superproxy.io
                      p_proxy_port=18889,  # 22225
                      p_proxy_username='',
                      p_proxy_password='',
                      p_timeout=10,
```

**Comment by ikvk** [comment]
TypeError: open() takes from 1 to 3 positional arguments but 4 were given

seems than python <= 3.8

**Comment by hongyi-zhao** [comment]
Do you mean I should test with python <= 3.8?

**Comment by ikvk** [comment]
No, I just described the error

**Comment by hongyi-zhao** [comment]
So, what should I do next?

**Comment by ikvk** [comment]
search - [AUTHENTICATIONFAILED] Invalid credentials (Failure)

**Comment by hongyi-zhao** [comment]
According to the notes [here](https://stackoverflow.com/questions/33119667/reading-gmail-is-failing-with-imap), I do the following:
```
1. Login into Gmail
2. Go to Google Account
3. Navigate to Security section
4. Turn on access for Less secure app access
```
This will fix the above error, but now I obtain the following very strange info when running the script with python 3.8:

```
$ python pysocks_proxy.py
Traceback (most recent call last):
  File "/home/werner/.pyenv/versions/3.8.3/lib/python3.8/imaplib.py", line 1022, in _command_complete
    typ, data = self._get_tagged_response(tag, expect_bye=logout)
  File "/home/werner/.pyenv/versions/3.8.3/lib/python3.8/imaplib.py", line 1148, in _get_tagged_response
    self._get_response()
  File "/home/werner/.pyenv/versions/3.8.3/lib/python3.8/imaplib.py", line 1050, in _get_response
    resp = self._get_line()
  File "/home/werner/.pyenv/versions/3.8.3/lib/python3.8/imaplib.py", line 1158, in _get_line
    line = self.readline()
  File "/home/werner/.pyenv/versions/3.8.3/lib/python3.8/imaplib.py", line 316, in readline
    raise self.error("got more than %d bytes" % _MAXLINE)
imaplib.error: got more than 4194304 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pysocks_proxy.py", line 196, in <module>
    for msg in mailbox.fetch():
  File "/home/werner/.pyenv/versions/socks5-haproxy/lib/python3.8/site-packages/imap_tools/mailbox.py", line 103, in fetch
    nums = tuple((reversed if reverse else iter)(self.search(criteria, charset)))[limit_range]
  File "/home/werner/.pyenv/versions/socks5-haproxy/lib/python3.8/site-packages/imap_tools/mailbox.py", line 61, in search
    search_result = self.box.search(charset, encoded_criteria)
  File "/home/werner/.pyenv/versions/3.8.3/lib/python3.8/imaplib.py", line 723, in search
    typ, dat = self._simple_command(name, 'CHARSET', charset, *criteria)
  File "/home/werner/.pyenv/versions/3.8.3/lib/python3.8/imaplib.py", line 1205, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/home/werner/.pyenv/versions/3.8.3/lib/python3.8/imaplib.py", line 1026, in _command_complete
    raise self.error('command: %s => %s' % (name, val))
imaplib.error: command: SEARCH => got more than 4194304 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/werner/.pyenv/versions/3.8.3/lib/python3.8/imaplib.py", line 1022, in _command_complete
    typ, data = self._get_tagged_response(tag, expect_bye=logout)
  File "/home/werner/.pyenv/versions/3.8.3/lib/python3.8/imaplib.py", line 1148, in _get_tagged_response
    self._get_response()
  File "/home/werner/.pyenv/versions/3.8.3/lib/python3.8/imaplib.py", line 1079, in _get_response
    raise self.abort("unexpected response: %r" % resp)
imaplib.abort: unexpected response: b'5058 615059 615060 615061 615062 615063 615064 615065 615066 615067 615068 615069 615070 615071 615072 615073 615074 615075 615076 615077 615078 615079 615080 615081 615082 615083 615084 6150
[...]
```
Regards,
HY

**Comment by ikvk** [comment]
Try to read docs,  for example about limit arg

**Comment by hongyi-zhao** [comment]
I tried with the following, but still meet the same error:
```python
        for msg in mailbox.fetch(limit=50):
            print(msg.subject, msg.date_str)
```
