### ISSUE TITLE
Invalid Syntax error while importing 

### ISSUE THREAD

**Issue by RanjithNair1980** [ikvk/imap_tools#141]
I get this error in my code while importing 
from imap_tools import MailBox
from imap_tools import A

C:\VIEWS Data Inserts\JiraSD\MailboxCheck>python GCSMailBox_Clear.py
Traceback (most recent call last):
  File "GCSMailBox_Clear.py", line 6, in <module>
    from imap_tools import A
  File "C:\Users\agadmin\AppData\Local\Programs\Python\Python35\lib\site-packages\imap_tools\__init__.py", line 5, in <module>
    from .query import AND, OR, NOT, Header, UidRange, A, O, N, H, U
  File "C:\Users\agadmin\AppData\Local\Programs\Python\Python35\lib\site-packages\imap_tools\query.py", line 85
    ):
    ^
SyntaxError: invalid syntax

**Comment by ikvk** [comment]
Thanks. https://github.com/ikvk/imap_tools/releases/tag/v0.49.1
