### ISSUE TITLE
module 'imaplib' has no attribute 'IMAP4_SSL'

### ISSUE THREAD

**Issue by rohaan2614** [ikvk/imap_tools#154]
Hey,

I keep getting this error:
```
Traceback (most recent call last):
  File "c:\Freelancing\gmail_poc\main.py", line 23, in <module>
    with MailBox('imap.mail.com').login(FROM_EMAIL, FROM_PWD ) as mailbox:
  File "C:\Users\Rohaan\anaconda3\envs\gmail_poc\lib\site-packages\imap_tools\mailbox.py", line 273, in __init__
    super().__init__()
  File "C:\Users\Rohaan\anaconda3\envs\gmail_poc\lib\site-packages\imap_tools\mailbox.py", line 34, in __init__
    self.box = self._get_mailbox_client()
  File "C:\Users\Rohaan\anaconda3\envs\gmail_poc\lib\site-packages\imap_tools\mailbox.py", line 290, in _get_mailbox_client
    return imaplib.IMAP4_SSL(self._host, self._port, self._keyfile,  # noqa
AttributeError: module 'imaplib' has no attribute 'IMAP4_SSL'
```

Maybe you can speciffy the python/package versions to use this with.

**Comment by ikvk** [comment]
Python 3.5+
Any package ver.
Make sure that you using python. Lib requires IMAP4_SSL in interpreter's imaplib

**Comment by rohaan2614** [comment]
I got these errors on Python 3.9.7

Tried it on my friend's machine and it was still the same. Can you please
share the version that you used to code this?

Thanks

**Comment by ikvk** [comment]
import imaplib
imaplib.IMAP4_SSL
<class 'imaplib.IMAP4_SSL'>

import sys
sys.version_info
sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)
