### ISSUE TITLE
Proxy support AWOL?

### ISSUE THREAD

**Issue by PuppyLover101** [ikvk/imap_tools#164]
```
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\PersonalEmailChecker\proxied.py", line 189, in <module>
    with MailBoxProxy(p_proxy_type=socks.HTTP,
  File "C:\Users\Admin\PycharmProjects\PersonalEmailChecker\proxied.py", line 179, in __init__
    super().__init__()
  File "C:\Users\Admin\PycharmProjects\PersonalEmailChecker\venv\lib\site-packages\imap_tools\mailbox.py", line 35, in __init__
    self.client = self._get_mailbox_client()
  File "C:\Users\Admin\PycharmProjects\PersonalEmailChecker\proxied.py", line 182, in _get_mailbox_client
    return Imap4SslProxy(
  File "C:\Users\Admin\PycharmProjects\PersonalEmailChecker\proxied.py", line 98, in __init__
    super().__init__(host, port, p_timeout, p_source_address, p_proxy_type, p_proxy_addr, p_proxy_port,
  File "C:\Users\Admin\PycharmProjects\PersonalEmailChecker\proxied.py", line 37, in __init__
    super().__init__(host, port)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\imaplib.py", line 202, in __init__
    self.open(host, port, timeout)
TypeError: open() takes from 1 to 3 positional arguments but 4 were given
```

I am using a 1:1 of the [example](https://raw.githubusercontent.com/ikvk/imap_tools/master/examples/pysocks_proxy.py), but there seems to be a problem with open()

Has MailBoxProxy been deprecated?

**Comment by ikvk** [comment]
seems yes

**Comment by ikvk** [comment]
Let me know if you cought fix it.

**Comment by ikvk** [comment]
related: https://github.com/ikvk/imap_tools/issues/128

**Comment by jezda** [comment]
I have same problem... open gives me error.. How to fix?

**Comment by AbdeLhalimSB** [comment]
I had the same problem but i fix it with adding this :
import socket
import socks
![image](https://user-images.githubusercontent.com/51211718/199964352-b5edf993-8eb1-4e04-abcc-f2862a83b6d6.png)

If you using normal proxy just remove the user & pass

**Comment by ikvk** [comment]
^up code
```
import socket
import socks
socks.setdefaultproxy(socks.PROXY_TYPE_HTTP, "proxy", int(port), True, "proxy_user", "proxy_pass")
socket.socket = socks.socksocket
with MailBox('mail.b.hostedemail.com').login(email, password, "Inbox") as mailbox:
```
