### ISSUE TITLE
1. Is there any limitation to query (fetch) gmail every 5 sec for unseen emails? 2. IDLE socket error: EOF

### ISSUE THREAD

**Issue by quammy** [ikvk/imap_tools#165]
Hi,
Thanks for an awesome library!

Maybe you know if there is any limitation to query (fetch) gmail every 5 sec for unseen emails? Will gmail block such process eventually?
Any info on the matter will be most welcome.

Thanks

**Comment by ikvk** [comment]
Hello
I think very frequently fetch will be ban on any public server. Try to use IDLE: 
https://github.com/ikvk/imap_tools#idle-workflow

**Comment by quammy** [comment]
Thanks @ikvk . Took me a while to make your sample work, till I noticed your comment about having the gmail account open on my browser. Now the idle with wait works as expected. There's only one thing left - once in a while I'm getting the error below.
Does this happen due to some internet connection instability? Or else, how can I avoid it?

```
2022-04-21 12:50:44 WARNING (camThread): cam1: Published admin notification: <module>: command: LOGOUT => socket error: EOF (Traceback (most recent call last):
  File "/app/app.py", line 35, in <module>
    responses = mailbox.idle.wait(timeout=3*60)
  File "/usr/local/lib/python3.9/site-packages/imap_tools/idle.py", line 121, in wait
    return idle.poll(timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/imap_tools/idle.py", line 128, in __exit__
    self.stop()
  File "/usr/local/lib/python3.9/site-packages/imap_tools/idle.py", line 60, in stop
    return self.mailbox.consume_until_tagged_response(self._idle_tag)
  File "/usr/local/lib/python3.9/site-packages/imap_tools/mailbox.py", line 54, in consume_until_tagged_response
    response: bytes = self.client._get_response()  # noqa, example: b'IJDH3 OK IDLE Terminated'
  File "/usr/local/lib/python3.9/imaplib.py", line 1075, in _get_response
    resp = self._get_line()
  File "/usr/local/lib/python3.9/imaplib.py", line 1185, in _get_line
    raise self.abort('socket error: EOF')
imaplib.IMAP4.abort: socket error: EOF
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/imaplib.py", line 1047, in _command_complete
    typ, data = self._get_tagged_response(tag, expect_bye=logout)
  File "/usr/local/lib/python3.9/imaplib.py", line 1173, in _get_tagged_response
    self._get_response()
  File "/usr/local/lib/python3.9/imaplib.py", line 1075, in _get_response
    resp = self._get_line()
  File "/usr/local/lib/python3.9/imaplib.py", line 1185, in _get_line
    raise self.abort('socket error: EOF')
imaplib.IMAP4.abort: socket error: EOF
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/app.py", line 67, in <module>
    connection_live_time = time.monotonic() - connection_start_time
  File "/usr/local/lib/python3.9/site-packages/imap_tools/mailbox.py", line 44, in __exit__
    self.logout()
  File "/usr/local/lib/python3.9/site-packages/imap_tools/mailbox.py", line 84, in logout
    result = self.client.logout()
  File "/usr/local/lib/python3.9/imaplib.py", line 642, in logout
    typ, dat = self._simple_command('LOGOUT')
  File "/usr/local/lib/python3.9/imaplib.py", line 1230, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/local/lib/python3.9/imaplib.py", line 1049, in _command_complete
    raise self.abort('command: %s => %s' % (name, val))
imaplib.IMAP4.abort: command: LOGOUT => socket error: EOF
```

**Comment by ikvk** [comment]
It is hard to say fo sure - it may by many reasons: in connection stability, in code, etc.

**Comment by ikvk** [comment]
Lets see your code

**Comment by quammy** [comment]
I used your exact code from [here](https://github.com/ikvk/imap_tools/blob/master/examples/idle.py) - example 2. I even kept the time of 3 * 60 and 29 * 60.

**Comment by ikvk** [comment]
Problems with connection are inevitable, I it happens rare - it is normal. 
How often it happens?
Of course there is a bug may be )

**Comment by quammy** [comment]
It happens once or twice every couple of days on a 24/7 always on service

**Comment by ikvk** [comment]
I think this is absolutely normal with that frequency.
There are me be many reasons for it.
If you will find something, let me know.

**Comment by quammy** [comment]
Ok, thanks. will surely do.
