### ISSUE TITLE
logout() error

### ISSUE THREAD

**Issue by tilkov** [ikvk/imap_tools#22]
Hi, trying to logout(), i've got errors on both Linux and Windows:
Connection is established with:

`with MailBox('mail.domain.com', port=993, ssl=True).login('username', 'password',initial_folder='Sent') as sent:`

On Linux (MailBox() as sent):

> Traceback (most recent call last):
  File "imap.py", line 8, in <module>
    sent.logout()
  File "/root/imapcrm/venv/lib/python3.5/site-packages/imap_tools/mailbox.py", line 69, in logout
    result = self.box.logout()
  File "/usr/lib/python3.5/imaplib.py", line 614, in logout
    self.shutdown()
  File "/usr/lib/python3.5/imaplib.py", line 312, in shutdown
    self.sock.shutdown(socket.SHUT_RDWR)
  File "/usr/lib/python3.5/ssl.py", line 967, in shutdown
    socket.shutdown(self, how)
OSError: [Errno 9] Bad file descriptor

On Windows (MailBox() as mailbox):

> Traceback (most recent call last):
  File "c:/Users/Todor/python/imapjson/imap.py", line 8, in <module>
    mailbox.logout()
  File "c:\Users\Todor\python\imapjson\venv\lib\site-packages\imap_tools\mailbox.py", line 69, in logout
    result = self.box.logout()
  File "C:\Users\Todor\AppData\Local\Programs\Python\Python38-32\lib\imaplib.py", line 633, in logout
    typ, dat = self._simple_command('LOGOUT')
  File "C:\Users\Todor\AppData\Local\Programs\Python\Python38-32\lib\imaplib.py", line 1205, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "C:\Users\Todor\AppData\Local\Programs\Python\Python38-32\lib\imaplib.py", line 983, in _command
    raise self.abort('socket error: %s' % val)
imaplib.abort: socket error: [WinError 10038] An operation was attempted on something that is not a socket

**Comment by ikvk** [comment]
Hi there.

I tried this:
```
with MailBox('imap.yandex.ru', port=993, ssl=True).login('hi@ya.ru', '*') as mailbox:
    for msg in mailbox.fetch():
        print(msg.date_str, msg.subject)
```
no fails.

File "c:/Users/Todor/python/imapjson/imap.py", line 8, in mailbox.logout()
Why are you call .logout()?
Check `MailBox.__exit__` src

Let me now any results.

**Comment by tilkov** [comment]
Hi!

It's a very simple test program, here's the complete source:

`from imap_tools import MailBox, Q

with MailBox('mail.domain.com', port=993, ssl=True).login('user', 'password',initial_folder='Sent') as sent:
    print("connected!")
    for message in sent.fetch(Q(to='otheruser@domain.com')):
        print(message.date_str)

sent.logout()
`

It outputs the email dates as it should, and then:

> Traceback (most recent call last):
  File "imap.py", line 8, in <module>
    sent.logout()
  File "/root/imapcrm/venv/lib/python3.5/site-packages/imap_tools/mailbox.py", line 69, in logout
    result = self.box.logout()
  File "/usr/lib/python3.5/imaplib.py", line 614, in logout
    self.shutdown()
  File "/usr/lib/python3.5/imaplib.py", line 312, in shutdown
    self.sock.shutdown(socket.SHUT_RDWR)
  File "/usr/lib/python3.5/ssl.py", line 967, in shutdown
    socket.shutdown(self, how)
OSError: [Errno 9] Bad file descriptor

**Comment by ikvk** [comment]
You should improve your python knowledge
https://docs.python.org/3/reference/datamodel.html#context-managers
And, then, check MailBox.__exit__ source code.
