### ISSUE TITLE
Error on closing connection 

### ISSUE THREAD

**Issue by mdogancay** [ikvk/imap_tools#248]
Code :
``` python
        def read_mails(self, mailbox_folder:str="INBOX"):
            # try:
            self.log.info(f"Connecting IMAP server: {self.config.imap_server} on port {self.config.imap_port}")
            # ssl_context = ssl.create_default_context()
            with MailBox( self.config.imap_server, self.config.imap_port, self.config.imap_timeout) as server:
                self.log.info(f"Connected.")
                self.log.info(f"Logging in with user {self.mail} into {mailbox_folder}")
                with server.login(self.mail, self.password, mailbox_folder) as mailbox:
                    self.log.info(f"Logged in")
                    for msg in mailbox.fetch():
                        print(f"{msg.uid} - {msg.subject}, {msg.date_str}")
```
error:
```
Traceback (most recent call last):
  File "Python311\Lib\imaplib.py", line 1006, in _command
    self.send(data + CRLF)
  File "Python311\Lib\imaplib.py", line 332, in send
    self.sock.sendall(data)
  File "Python311\Lib\ssl.py", line 1276, in sendall
    return super().sendall(data, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 10038] An operation was attempted on something that is not a socket

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "\utils\mail_service.py", line 172, in <module>       
    ms.read_mails()
  File "\utils\mail_service.py", line 116, in read_mails     
    with MailBox( self.config.imap_server, self.config.imap_port, self.config.imap_timeout) as server:
  File "\.venv\Lib\site-packages\imap_tools\mailbox.py", line 42, in __exit__
    self.logout()
  File "\.venv\Lib\site-packages\imap_tools\mailbox.py", line 94, in logout
    result = self.client.logout()
             ^^^^^^^^^^^^^^^^^^^^
  File "Python311\Lib\imaplib.py", line 642, in logout
    typ, dat = self._simple_command('LOGOUT')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Python311\Lib\imaplib.py", line 1230, in _simple_command
    return self._command_complete(name, self._command(name, *args))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Python311\Lib\imaplib.py", line 1008, in _command
    raise self.abort('socket error: %s' % val)
imaplib.IMAP4.abort: socket error: [WinError 10038] An operation was attempted on something that is not a socket
```

**Comment by mdogancay** [comment]
> Try to read:
> 
> 1. https://github.com/ikvk/imap_tools/blob/master/examples/basic.py (link from proj home)
> 2. About context manager
> 
> See on .login
thank you for fast reply. but there is no logout on my code. even all the code is up there.
i run this code 2 different machine with python 3.11 and all the same.
i am using python 3.11 ( i didn't wrote the issue because on the log u can see)

**Comment by mdogancay** [comment]
You are using:
''' python
with MailBox('imap.mail.com').login('test@mail.com', 'pwd') as mailbox:
    for msg in mailbox.fetch():
        print(msg.date, msg.subject, len(msg.text or msg.html))
'''
and i am using:
''' python
with MailBox('imap.mail.com') as server:
    with server.login('test@mail.com', 'pwd') as mailbox:
        for msg in mailbox.fetch():
            print(msg.date, msg.subject, len(msg.text or msg.html))
'''
I think the problem is here
