### ISSUE TITLE
Error on closing connection

### ISSUE THREAD

**Issue by mdogancay** [ikvk/imap_tools#250]
if i use this syntax (i am not using any logout command all the code is down there):
```python
with MailBox('imap.mail.com') as server:
    with server.login('test@mail.com', 'pwd') as mailbox:
        for msg in mailbox.fetch():
            print(msg.date, msg.subject, len(msg.text or msg.html))
```
i got this error:
```
Traceback (most recent call last):
  File "Python311\Lib\imaplib.py", line 1006, in _command
    self.send(data + CRLF)
  File "Python311\Lib\imaplib.py", line 332, in send
    self.sock.sendall(data)
  File "Python311\Lib\ssl.py", line 1276, in sendall
    return super().sendall(data, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 10038] An operation was attempted on something that is not a socket

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "\utils\mail_service.py", line 172, in <module>       
    ms.read_mails()
  File "\utils\mail_service.py", line 116, in read_mails     
    with MailBox( self.config.imap_server, self.config.imap_port, self.config.imap_timeout) as server:
  File "\.venv\Lib\site-packages\imap_tools\mailbox.py", line 42, in __exit__
    self.logout()
  File "\.venv\Lib\site-packages\imap_tools\mailbox.py", line 94, in logout
    result = self.client.logout()
             ^^^^^^^^^^^^^^^^^^^^
  File "Python311\Lib\imaplib.py", line 642, in logout
    typ, dat = self._simple_command('LOGOUT')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Python311\Lib\imaplib.py", line 1230, in _simple_command
    return self._command_complete(name, self._command(name, *args))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Python311\Lib\imaplib.py", line 1008, in _command
    raise self.abort('socket error: %s' % val)
imaplib.IMAP4.abort: socket error: [WinError 10038] An operation was attempted on something that is not a socket
```

**Comment by ikvk** [comment]
Read:
1. About context manager
2. https://github.com/ikvk/imap_tools/blob/master/examples/basic.py (link from proj home)

You have double __exit__

You don't have to be stubborn, you need to read the docks and know your tools

**Comment by ikvk** [comment]
```
with MailBox('imap.mail.com').login('test@mail.com', 'pwd') as mailbox:
    for msg in mailbox.fetch():
        print(msg.date, msg.subject, len(msg.text or msg.html))
```
