### ISSUE TITLE
pysocks_proxy.py not work

### ISSUE THREAD

**Issue by dashaleonova8003** [ikvk/imap_tools#85]
```
Traceback (most recent call last):
  File "C:\pysocks_proxy.py", line 189, in <module
    with MailBoxProxy(p_proxy_type=socks.HTTP,
  File "C:\pysocks_proxy.py", line 179, in __init__
    super().__init__()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\imap_tools\mailbox.py", line 26, in __init__
    self.box = self._get_mailbox_client()
  File "C:\pysocks_proxy.py", line 182, in _get_mailbox_client
    return Imap4SslProxy(
  File "C:\pysocks_proxy.py", line 98, in __init__
    super().__init__(host, port, p_timeout, p_source_address, p_proxy_type, p_proxy_addr, p_proxy_port,
  File "C:\pysocks_proxy.py", line 37, in __init__
    super().__init__(host, port)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\imaplib.py", line 202, in __init__
    self.open(host, port, timeout)
TypeError: open() takes from 1 to 3 positional arguments but 4 were given
```

**Comment by ikvk** [comment]
script not adapted to 3.9, timeout arg appeared there
