### ISSUE TITLE
How to deal with imaplib.abort exception on imap_tools?

### ISSUE THREAD

**Issue by yellowcox** [ikvk/imap_tools#96]
Hi,
First, thx for your works! 
I use imap_tools for fetching mail from gmail, it's working well, but sometimes, I have to deal with exception and I don't know how to catch this:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/imaplib.py", line 1019, in _command_complete
    typ, data = self._get_tagged_response(tag)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/imaplib.py", line 1139, in _get_tagged_response
    self._get_response()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/imaplib.py", line 1047, in _get_response
    resp = self._get_line()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/imaplib.py", line 1151, in _get_line
    raise self.abort('socket error: EOF')
imaplib.abort: socket error: EOF
```

I use imap-tools v0.37 with the function :
```
with MailBox(host).login(username, password, folderCheck) as mailbox:
    for msg in mailbox.fetch(AND(from_=sender, subject=subjectSearch)):
```
I would like to retry if something wrong with a try/except
Can you help me?
Thx

**Comment by ikvk** [comment]
Greeting. 
Seems that server brake connection. 
I think it is impossible to do something except reconnect.

**Comment by yellowcox** [comment]
Yes but how to use try/except under imap_tools with a imaplib exception?
For reconnect and not crash
I try
`except imaplib.abort:`
but it's not defined

**Comment by ikvk** [comment]
try to explore imaplib.py src
```
import imaplib
imaplib.IMAP4.abort
<class 'imaplib.IMAP4.abort'>
```
